### PR TITLE
ci: add lint, links, gosec and depbot

### PR DESCRIPTION
**Pull request by pratikbin**
- Lint CI for linting project
- Gosec golang security checker
- Links ci for checking broker links in docs
- Dependabot for dep update
- Codeql for semantic code analysis engine

### CODE REVIEW

**Comment by Naman2706** [comment]
@pratikbin please rebase

**Comment by pratikbin** [comment]
`rebase` ci will force push, @aman00323 How dangerous it is?

**Comment by aman00323** [comment]
@pratikbin can't rely on right now

**Comment by pratikbin** [comment]
> 

You mean remove it ?

**Comment by aman00323** [comment]
Yes, force push might ruin someone's work.

**Comment by pratikbin** [comment]
Thought so checked for flags but didn't find any. removing it

**Review by vyas-shyam — APPROVED** [review]

**Review by Naman2706 — APPROVED** [review]

**Comment by pratikbin** [comment]
Squash merge it please

**Pull request merged**
